#!/bin/bash
######
#SBATCH --nodes=40
#SBATCH --ntasks-per-node=7
#SBATCH --cpus-per-task=4
#####
#SBATCH -J NEPTUNE_MAKESTART
#SBATCH --time=00:05:00
#SBATCH --output job_omp_mpi.%j.out
#SBATCH --constraint=BDW28
#SBATCH --exclusive

export EXEC_NAME=./icosa_lmdz.exe

set -vx

source ../../trunk/ARCH/arch-X64_OCCIGEN.env
ulimit -s unlimited

#printenv | sort
#Make sure that OMP_NUM_THREADS = cpus-per-task * KMP_HW_SUBSET
export KMP_HW_SUBSET=1T
export OMP_NUM_THREADS=4
export OMP_STACKSIZE=256M
export KMP_AFFINITY=granularity=fine,compact,1,0,verbose

nproc=$((SLURM_NTASKS-2))
nlast=$((SLURM_NTASKS-1))
echo "# srun configuration file" > srun.conf
echo "0-$nlast icosa_lmdz.exe" >> srun.conf

### just one
srun --resv-ports --kill-on-bad-exit=1 --mpi=pmi2 --label -c $OMP_NUM_THREADS -n $SLURM_NTASKS --multi-prog srun.conf > icosa_lmdz.out 2>&1
exit

count=1
##############
limcount=$((count+1)) #24h
while [ $count -lt $limcount ]
do
  echo "**************************************"
  echo "RUN NUMBER "$count
  echo "**************************************"
  ##
  ln -sf start_icosa_$count.nc start_icosa.nc
  ln -sf startfi_$count.nc     startfi.nc
  ##
  srun --resv-ports --kill-on-bad-exit=1 --mpi=pmi2 --label -c $OMP_NUM_THREADS -n $SLURM_NTASKS --multi-prog srun.conf > icosa_lmdz.out 2>&1
  ##
  sleep 30
  mv Xhistins.nc      Xhistins_$count".nc"
  mv icosa_lmdz.out   icosa_lmdz_$count".out"
  ##
  count=$((count+1))
  mv restart_icosa.nc start_icosa_$count".nc"
  mv restartfi.nc     startfi_$count".nc"
done



