#!/bin/bash
### set --threads-per-core=2 for hyperthreading
#SBATCH --threads-per-core=1
#SBATCH -J JUPITER_MAKESTART
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=10
#SBATCH --time=23:59:00
#SBATCH --output job_mpi.%j.out
#SBATCH --constraint=BDW28
##SBATCH --constraint=HSW24
#SBATCH --exclusive
#SBATCH --mem=57000MB
###SBATCH -p all
###SBATCH -p highmem

#export EXEC_NAME=/scratch/cnt0026/lmd7357/aspigaheat/MODELES/ICOSA_LMDZ/bin/icosa_lmdz.exe
export EXEC_NAME=./icosa_lmdz.exe

set -vx

source ../../code/ARCH/arch-X64_OCCIGEN.env
ulimit -s unlimited

#printenv | sort
export OMP_NUM_THREADS=1
export OMP_STACKSIZE=256M
export KMP_AFFINITY=granularity=fine,compact,1,0,verbose

nproc=$((SLURM_NTASKS-1))
nlast=$((SLURM_NTASKS-1))
echo "# srun configuration file" > srun.conf
echo "0-$nproc icosa_lmdz.exe" >> srun.conf
#echo "$nlast xios_server.exe" >> srun.conf
#ln -sf srun.conf.$SLURM_NTASKS srun.conf

## just one
srun --resv-ports --kill-on-bad-exit=1 --mpi=pmi2 --label -c $OMP_NUM_THREADS -n $SLURM_NTASKS --multi-prog srun.conf > icosa_lmdz.out 2>&1
exit




