#!/bin/bash
##### TEST EHOUARN
##SBATCH --nodes=1
##SBATCH --ntasks-per-node=10
######
##SBATCH --nodes=2
##SBATCH --ntasks-per-node=20
###### TEST MPI 
#SBATCH --nodes=200
#SBATCH --ntasks-per-node=24
##SBATCH --cpus-per-task=1
#####
### set --threads-per-core=2 for hyperthreading
#SBATCH --threads-per-core=1
#SBATCH -J SATURN
#SBATCH --time=00:10:00
#SBATCH --output job_mpi.%j.out
###SBATCH --constraint=BDW28
#SBATCH --constraint=HSW24
#SBATCH --exclusive
##SBATCH --mem=120G
###SBATCH -p all
###SBATCH -p highmem
##SBATCH --qos=bonus


#export EXEC_NAME=/scratch/cnt0026/lmd7357/aspigaheat/MODELES/ICOSA_LMDZ/bin/icosa_lmdz.exe
export EXEC_NAME=./icosa_lmdz.exe

#### LIMITS
#ulimit -l unlimited  ## requested in logs
#ulimit -s unlimited  ## test
#ulimit -v unlimited
#ulimit -a
#ulimit -aH

set -vx

source ../code/ARCH/arch-X64_OCCIGEN.env


#printenv | sort
export OMP_NUM_THREADS=1
export OMP_STACKSIZE=256M
export KMP_AFFINITY=granularity=fine,compact,1,0,verbose

nproc=$((SLURM_NTASKS-2))
nlast=$((SLURM_NTASKS-1))
echo "# srun configuration file" > srun.conf
echo "0-$nproc icosa_lmdz.exe" >> srun.conf
echo "$nlast xios_server.exe" >> srun.conf

## just one
srun --resv-ports --kill-on-bad-exit=1 --mpi=pmi2 --label -c $OMP_NUM_THREADS -n $SLURM_NTASKS --multi-prog srun.conf > icosa_lmdz.out 2>&1
exit

### 1200: see run_icosa.def 10*nsplit_i*nsplit_j
### 24(SLURM_JOB_NUM_NODES - 50) gives number of XIOS servers
#build_srun_conf.bash -nodes $SLURM_JOB_NUM_NODES -cores 1200

### just one
#srun --resv-ports --kill-on-bad-exit=1 --mpi=pmi2 --label -c $OMP_NUM_THREADS -n $SLURM_NTASKS --multi-prog srun.conf > icosa_lmdz.out 2>&1
#exit

count=1
count=22
count=43
count=64
count=85
count=106
count=107 # passe a 720x360
count=128
#count=11
#count=21
count=1 # avec zero perturb
count=22
count=43
count=45
count=66
count=85
count=106
count=112
count=132
count=153
count=163
count=184
count=205
count=226
count=247
count=266
count=1
##############
#limcount=$((count+15)) #12h
#limcount=$((count+30)) #24h
limcount=$((count+1)) #24h
while [ $count -lt $limcount ]
do
  echo "**************************************"
  echo "RUN NUMBER "$count
  echo "**************************************"
  ##
  ln -sf start_icosa_$count.nc start_icosa.nc
  ln -sf startfi_$count.nc     startfi.nc
  ##
  srun --resv-ports --kill-on-bad-exit=1 --mpi=pmi2 --label -c $OMP_NUM_THREADS -n $SLURM_NTASKS --multi-prog srun.conf > icosa_lmdz.out 2>&1
  ##
  sleep 30
  mv Xhistins.nc      Xhistins_$count".nc"
  mv icosa_lmdz.out   icosa_lmdz_$count".out"
  ##
  count=$((count+1))
  mv restart_icosa.nc start_icosa_$count".nc"
  mv restartfi.nc     startfi_$count".nc"
done



