#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --threads-per-core=1
#SBATCH -J SATURN1D
#SBATCH --time=06:00:00
#SBATCH --constraint=HSW24
srun --mpi=pmi2 -K1 -n $SLURM_NTASKS ./rcm1d.e > rcm1d.log




