#!/bin/bash
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=20
### set --threads-per-core=2 for hyperthreading
#SBATCH --threads-per-core=1
#SBATCH -J SATURN
#SBATCH --time=00:45:00
#SBATCH --output job_mpi.%j.out
###SBATCH --constraint=BDW28
#SBATCH --constraint=HSW24
#SBATCH --exclusive
#SBATCH --mem=110G

export EXEC_NAME=./icosa_lmdz.exe

set -vx


source ../../code/ARCH/arch-X64_OCCIGEN.env
ulimit -s unlimited

#printenv | sort
export OMP_NUM_THREADS=1
export OMP_STACKSIZE=256M
export KMP_AFFINITY=granularity=fine,compact,1,0,verbose

nproc=$((SLURM_NTASKS-1))
echo "# srun configuration file" > srun.conf
echo "0-$nproc icosa_lmdz.exe" >> srun.conf

## just one
srun --resv-ports --kill-on-bad-exit=1 --mpi=pmi2 --label -c $OMP_NUM_THREADS -n $SLURM_NTASKS --multi-prog srun.conf > icosa_lmdz.out 2>&1
exit




